name: music_studio_assignment
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/pngs/


  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/syne/Syne-Regular.ttf
          weight: 300
        - asset: assets/fonts/syne/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/syne/Syne-Bold.ttf
          weight: 700

    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster/Lobster-Regular.ttf
